inputs:
  workflowPath:
    description: Path to CWL workflow to preserve in EaaS
    required: true
  eaasBackendUrl:
     description: EaaS backend base URL (usually ends with "/emil")
     required: true
  runtimeId:
    description: Container runtime ID in EaaS instance
    required: true
  repoUrl:
    description: Git URL of the original CWL Repo
    required: false
  branch:
    description: Target Branch for the Rewriter Results
    required: false

name: CWL Rewriter
description: Rewriter Action for CWL Files
runs:
  using: "composite"
  steps:
  - run: |
      pip install -r "$GITHUB_ACTION_PATH"/requirements.txt
      echo "Done with installing dependencies..."
      "$GITHUB_ACTION_PATH"/rewriter.py --runtime-id "$runtimeId" "$workflowPath"
    shell: bash
    env:
      runtimeId: ${{inputs.runtimeId}}
      workflowPath: ${{inputs.workflowPath}}
      EMIL_BASE_URL: ${{inputs.eaasBackendUrl}}

  - run: |
      git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git config --local user.name "github-actions[bot]"
      git checkout ${{inputs.branch}}
      git add  **/wrapped_*.cwl
      git commit -a -m "Automated commit of rewritten files from branch: ${{github.head_ref}}"
    shell: bash
    if: ${{inputs.repoUrl}} != ''
  - uses: actions/upload-artifact@v3
    with:
      name: Preserved CWL workflows for ${{inputs.workflowPath}}
      path: |
        **/wrapped_*.cwl
